### ISSUE TITLE
Traceroute

### ISSUE THREAD

**Issue by ashudb70** [himanshurawlani/NetworkingTools#1]
Traceroute doesn't function in cellular data connection mode how to fix it

**Comment by himanshurawlani** [comment]
Cellular data connection is usually slow and takes more time compared to WiFi connection. Traceroute will work on cellular network but will take a lot of time to give output. Also it depends on the router, on which the Time to live (ttl) becomes 1, is configured to respond back to the source.
As you may see in Linux when you use traceroute command it gives you 3 stars ( * * * ) in output because of no reply from the routers.

**Comment by ashudb70** [comment]
yes so atleaset can i show that 3 *** ur code is very useful m using refrence for my college project so i needed your help how can i implement that feature on celllular network or show 3 ***
can u paste the code?

**Comment by himanshurawlani** [comment]
I would encourage you to search for it on Google and do it on your own. Trust me it's not that tough. Good luck !

**Comment by ashudb70** [comment]
i can buy you a cofee

**Comment by ashudb70** [comment]
please help me a lil bit atleast where to make change please
